import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./styles/index.css";
import "./styles/cube.css";
import "./styles/cube1.css";
import "./styles/cube2.css";
import "./styles/Loader.css";
import "./styles/Main.css";
import "./styles/MainHome.css";
import "./styles/Header.css";
import "./styles/HeaderFoto.css";
import "./styles/Footer.css";
import "./styles/FooterFoto.css";
import "./styles/HeaderVideo.css";
import "./styles/HeaderCV.css";
import "./App.css";

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<App />);
